import * as React from 'react';
import { 
  DataGrid, 
  GridToolbarContainer, 
  GridToolbar } from '@material-ui/data-grid';
import { container } from '@aws-amplify/ui';



function CustomToolbar() {
  return (
    <GridToolbarContainer>
      <GridToolbar />
    </GridToolbarContainer>
  );
}


  export default function ColumnSizingGrid() {
    return (

          <div style={{ height: 1200,  width: '100%' }}>
            <container>
            <DataGrid rows={rows} columns={columns} checkboxSelection
                components={{
                  Toolbar: GridToolbar 
                }}
                />
                </container>
    </div>
  );
}
const columns = [
  { field: 'id',  headerName: 'BOMid',  width: 120,  editable: false }, 
  { field: 'part_num',  headerName: 'Part',  width: 300,  editable: false }, 
 
  { field: 'description',  headerName: 'Description',  width: 300,  editable: false }, 
  { field: 'responsible_engineer_name',  headerName: 'Lead Eng',  width: 120,  editable: false }, 
  { field: 'responsible_engineer_alias',  headerName: 'Lead Eng @',  width: 180,  editable: false }, 
  { field: 'tpm_name',  headerName: 'Lead TPM',  width:120,  editable: true }, 
  { field: 'tpm_alias',  headerName: 'Lead TPM @',  width:180,  editable: true }, 
  { field: 'data_source',  headerName: 'Data Source',  width: 150,  editable: true }, 
  { field: 'source_data_link',  headerName: 'Source Link',  width: 200,  editable: true }, 
  { field: 'next_higher_assembly',  headerName: 'Higher Assembly',  width: 300,  editable: false }, 
  { field: 'L0',  headerName: 'Lvl0',  width: 300,  editable: false }, 
  { field: 'L1',  headerName: 'Lvl1',  width: 300,  editable: false }, 
  { field: 'L2',  headerName: 'Lvl2',  width: 300,  editable: false }, 
  { field: 'L3',  headerName: 'Lvl3',  width: 300,  editable: false }, 
  { field: 'L4',  headerName: 'Lvl4',  width: 300,  editable: false }, 
  { field: 'L5',  headerName: 'Lvl5',  width: 300,  editable: false }, 
  { field: 'L6',  headerName: 'Lvl6',  width: 300,  editable: false }, 
  { field: 'L7',  headerName: 'Lvl7',  width: 300,  editable: false }, 
  { field: 'level',  headerName: 'Part Lvl',  width: 300,  editable: false }, 
  { field: 'parent_nomenclature',  headerName: 'Parent Nom',  width: 300,  editable: false }, 
  { field: 'manufacturer_part_num',  headerName: 'Mfr. Part #',  width: 300,  editable: false }, 
  { field: 'purchasable_item',  headerName: 'Purch Item',  width: 300,  editable: false }, 
  { field: 'qty_for_build',  headerName: 'Build Qty',  width: 300,  editable: true }, 
  { field: 'need_by_date',  headerName: 'Need By',  width: 300, type: 'date', editable: true }, 
  { field: 'revision',  headerName: 'Rev',  width: 300,  editable: true}, 
];

const rows = [
  
  {
    id: 2320,
    part_num: "999999-999 SADA Controller",
    next_higher_assembly: "nan",
    description: "999999-999 SADA Controller",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 SADA Controller",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Tim Coomes",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 25,
    need_by_date: "6/16/2021",
    
    } , {
    id: 2498,
    part_num: "999999-999 FRED",
    next_higher_assembly: "nan",
    description: "999999-999 FRED",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 FRED",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Tim Coomes",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 35,
    need_by_date: "8/4/2021",
    
    } , {
    id: 4244,
    part_num: "999999-999 Backplane",
    next_higher_assembly: "nan",
    description: "999999-999 Backplane",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 Backplane",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "null",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 15,
    need_by_date: "5/1/2021",
    
    } , {
    id: 4251,
    part_num: "999999-999 OHA-BEO-PROTO0",
    next_higher_assembly: "nan",
    description: "999999-999 OHA-BEO-PROTO0",
    parts_category: 12,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 OHA-BEO-PROTO0",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'Mentor',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Donald Cornwell",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 25,
    need_by_date: "5/24/2021",
    
    } , {
    id: 4301,
    part_num: "999999-999 OHA-ECTS-PROTO0",
    next_higher_assembly: "nan",
    description: "999999-999 OHA-ECTS-PROTO0",
    parts_category: 12,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 OHA-ECTS-PROTO0",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'Mentor',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Donald Cornwell",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 20,
    need_by_date: "4/23/2021",
    
    } , {
    id: 2122,
    part_num: "999999-999 Prescott PCU",
    next_higher_assembly: "nan",
    description: "999999-999 Prescott PCU",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 Prescott PCU",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Tim Coomes",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 15,
    need_by_date: "4/9/2021",
    
    } , {
    id: 4337,
    part_num: "999999-999 OTAC-CONTROL_BOARD-EM1",
    next_higher_assembly: "nan",
    description: "999999-999 OTAC-CONTROL_BOARD-EM1",
    parts_category: 12,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 OTAC-CONTROL_BOARD-EM1",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'Mentor',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Donald Cornwell",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 20,
    need_by_date: "5/14/2021",
    } , {
    id: 2999,
    part_num: "999999-999 SGT",
    next_higher_assembly: "nan",
    description: "999999-999 SGT",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 SGT",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Kevin Larsson",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 42,
    need_by_date: "6/2/2021",
    
    } , {
    id: 4201,
    part_num: "999999-999 GNSS_FE",
    next_higher_assembly: "nan",
    description: "999999-999 GNSS_FE",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 GNSS_FE",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "null",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: null,
    need_by_date: "null",
    
    } , {
    id: 4234,
    part_num: "999999-999 BOB",
    next_higher_assembly: "nan",
    description: "999999-999 BOB",
    parts_category: 4,
    L0: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L1: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L2: "100100-201/01-KUIPER PRODUCTION SATELLITE ASSEMBLY",
    L3: "999999-999 BOB",
    L4: null,
    L5: null,
    L6: null,
    L7: null,
    level: 3,
    data_source: 'S3',
    source_data_link: null,
    responsible_engineer_name: null,
    responsible_engineer_alias: null,
    tpm_name: "Trevor Fayer",
    tpm_alias: null,
    manufacturer_part_num: null,
    revision: 1,
    qty_for_build: 55,
    need_by_date: "4/30/2021",
    }];